M48
; DRILL file {KiCad 9.0.7} date 2026-02-15T19:18:06+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-15T19:18:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X118.6Y-49.48
X118.6Y-97.48
X151.6Y-49.48
X151.6Y-97.48
T2
X118.6Y-26.995
X118.6Y-38.425
M30
